# Generated by Django 5.2.5 on 2025-09-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tienda'),
        ),
    ]
