# Generated by Django 5.2.5 on 2025-09-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_producto_categoria_producto_tienda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'ordering': ['-id'], 'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='link',
            field=models.URLField(blank=True, verbose_name='Enlace del producto'),
        ),
    ]
