# Generated by Django 5.2.5 on 2025-09-15 22:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_proposals_and_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tienda',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Tienda'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación'),
        ),
    ]
